// <auto-generated />
using System;
using ImperialColors.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImperialColors.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624183717_AddPerformanceIndexesV2")]
    partial class AddPerformanceIndexesV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImperialColors.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("tipo_pessoa");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("tipo_pessoa");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemListaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<bool>("Comprado")
                        .HasColumnType("boolean")
                        .HasColumnName("comprado");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DescricaoItem")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao_item");

                    b.Property<int>("ListaCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("lista_compra_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal?>("QuantidadeComprada")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_comprada");

                    b.Property<decimal>("QuantidadeDesejada")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_desejada");

                    b.HasKey("Id");

                    b.HasIndex("ListaCompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("itens_lista_compra", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemVendaExterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_produto");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_base");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("VendaExternaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_externa_id");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaExternaId");

                    b.ToTable("itens_venda_externa", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ListaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizada");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<byte[]>("NotaFiscalConteudo")
                        .HasColumnType("bytea")
                        .HasColumnName("nota_fiscal_conteudo");

                    b.Property<string>("NotaFiscalNomeArquivo")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nota_fiscal_nome_arquivo");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("listas_compra", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("QuantidadeAnterior")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_anterior");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_atual");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<int?>("VendaExternaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_externa_id");

                    b.Property<int?>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaExternaId");

                    b.HasIndex("VendaId");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ParametroSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("ValorData")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("valor_data");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor_texto");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("parametros_sistema", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_interno");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal?>("Custo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("custo");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_validade");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("estoque_minimo");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<decimal?>("LitragemGl")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("litragem_gl");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal?>("PrecoPromocional")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_promocional");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<bool>("PromocaoAtiva")
                        .HasColumnType("boolean")
                        .HasColumnName("promocao_ativa");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_estoque");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("CodigoInterno")
                        .IsUnique();

                    b.HasIndex("FornecedorId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("Nome");

                    b.HasIndex("PromocaoAtiva");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Troca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataTroca")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_troca");

                    b.Property<int?>("FormaPagamentoDiferenca")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento_diferenca");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int>("ProdutoDevolvidoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_devolvido_id");

                    b.Property<int>("ProdutoNovoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_novo_id");

                    b.Property<decimal>("QuantidadeDevolvida")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_devolvida");

                    b.Property<decimal>("QuantidadeNova")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantidade_nova");

                    b.Property<bool>("RetornarAoEstoque")
                        .HasColumnType("boolean")
                        .HasColumnName("retornar_ao_estoque");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<decimal>("ValorUnitarioDevolucao")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_unitario_devolucao");

                    b.Property<decimal>("ValorUnitarioNovo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_unitario_novo");

                    b.Property<int?>("VendaExternaOrigemId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_externa_origem_id");

                    b.Property<int?>("VendaOrigemId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_origem_id");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoDevolvidoId");

                    b.HasIndex("ProdutoNovoId");

                    b.HasIndex("VendaExternaOrigemId");

                    b.HasIndex("VendaOrigemId");

                    b.ToTable("trocas", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<int>("Permissao")
                        .HasColumnType("integer")
                        .HasColumnName("permissao");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("salt");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_venda");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("DocumentoCompradorCupom")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_comprador_cupom");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("NomeCompradorCupom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_comprador_cupom");

                    b.Property<string>("NumeroVenda")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_venda");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("QuantidadeParcelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade_parcelas");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<int?>("TipoPessoaComprador")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_pessoa_comprador");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("Troco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("troco");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataVenda");

                    b.HasIndex("NumeroVenda")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.VendaExterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_venda");

                    b.Property<string>("NumeroVendaExterna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_venda_externa");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("DataVenda");

                    b.HasIndex("NumeroVendaExterna")
                        .IsUnique();

                    b.ToTable("vendas_externas", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.VendaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("QuantidadeParcelas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantidade_parcelas");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorRecebido")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_recebido");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("venda_pagamentos", (string)null);
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemListaCompra", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.ListaCompra", "ListaCompra")
                        .WithMany("Itens")
                        .HasForeignKey("ListaCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImperialColors.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensListaCompra")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ListaCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialColors.Domain.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ItemVendaExterna", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImperialColors.Domain.Entities.VendaExterna", "VendaExterna")
                        .WithMany("Itens")
                        .HasForeignKey("VendaExternaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("VendaExterna");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ListaCompra", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("ListasCompra")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialColors.Domain.Entities.VendaExterna", "VendaExterna")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("VendaExternaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImperialColors.Domain.Entities.Venda", "Venda")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Produto");

                    b.Navigation("Venda");

                    b.Navigation("VendaExterna");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Produto", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImperialColors.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Produtos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ImperialColors.Domain.Entities.Marca", "Marca")
                        .WithMany("Produtos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Fornecedor");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Troca", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Produto", "ProdutoDevolvido")
                        .WithMany()
                        .HasForeignKey("ProdutoDevolvidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialColors.Domain.Entities.Produto", "ProdutoNovo")
                        .WithMany()
                        .HasForeignKey("ProdutoNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImperialColors.Domain.Entities.VendaExterna", "VendaExternaOrigem")
                        .WithMany()
                        .HasForeignKey("VendaExternaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ImperialColors.Domain.Entities.Venda", "VendaOrigem")
                        .WithMany()
                        .HasForeignKey("VendaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProdutoDevolvido");

                    b.Navigation("ProdutoNovo");

                    b.Navigation("VendaExternaOrigem");

                    b.Navigation("VendaOrigem");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Venda", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.VendaPagamento", b =>
                {
                    b.HasOne("ImperialColors.Domain.Entities.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Fornecedor", b =>
                {
                    b.Navigation("ListasCompra");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.ListaCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Marca", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensListaCompra");

                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("ImperialColors.Domain.Entities.VendaExterna", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
